apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: dashboard-tls
  namespace: kubernetes-dashboard
spec:
  secretName: dashboard-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: dash-k8s.duckdns.org
  dnsNames:
  - dash-k8s.duckdns.org
  usages:
  - digital signature
  - key encipherment
  - server auth
